### PR TITLE
Added credits ConVar.

### PR DESCRIPTION
**Pull request by Drixevel-Archive**
It's easier to edit the ConVar, my circumstance calls for it.

### CODE REVIEW

**Comment by kebokyo** [comment]
What credits?

**Comment by Drixevel-Archive** [comment]
End-game credits. The original value/location was 'scripts/credits.txt' based on a define. I was wanting the ability to set the path to that file so it can be edited since my game/mod had an older version I did as a project during college that had a certain credits file.

**Comment by kebokyo** [comment]
Um... I feel like that's too small of a change to be included, but hey, we might. I can't merge, so someone like @DankParrot will have to decide.

**Comment by kebokyo** [comment]
Plus, you could do it in-code because you don't need to change it in-game.

**Comment by Drixevel-Archive** [comment]
I do based on what I'm doing. The plan is to add a custom console command which loads a level and once that level is finished by the player, a different set of credits should play entirely. I used a 'point_servercommand' entity to just set the clients credits that way. Without this, there's only 1 file I can use in the engine and that's not what I'm wanting.

I figured I'd push this since It's relatively small and could be useful to others as well but your call.

**Comment by kebokyo** [comment]
Again, I can't merge the branch; I'm not authorized.
screenshot 2016-11-29 at 8 04 18 am
I guess we could. It's not going to break anything.

**Comment by kebokyo** [comment]
@DankParrot @Jesse-Culver @SourceCommunityEditionTeam/managers What do you guys think?

**Comment by kebokyo** [comment]
Oh, and I made a new team for the people who have direct access to the master branch so you can spam @ at them to get their attention.
@SourceCommunityEditionTeam/developers if you can directly push commits to the master branch, join the Managers team.

**Pull request merged**
